# Generated by Django 2.0.5 on 2018-06-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='price_w_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
