# Generated by Django 2.0.5 on 2018-06-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_remove_product_price_w_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_w_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
