# Generated by Django 2.0.5 on 2018-06-25 10:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_productincart'),
    ]

    operations = [
        migrations.AddField(
            model_name='productincart',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productincart',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
