# Generated by Django 2.0.5 on 2018-06-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20180625_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='productincart',
            name='image_url',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
