# Generated by Django 2.0.5 on 2018-07-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_productincart_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cusomer_phone',
            field=models.CharField(blank=True, default=None, max_length=14, null=True),
        ),
    ]
