# Generated by Django 2.0.5 on 2018-07-10 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_cusomer_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cusomer_phone',
            new_name='customer_phone',
        ),
    ]
